"use client";

import { useState, useRef, useEffect } from "react";
import { Download, Calendar, FileText, ChevronDown } from "lucide-react";
import { googleCalendarUrl, buildActivityDateRange } from "@/lib/calendar";

interface Activity {
  title: string;
  description?: string | null;
  address?: string | null;
  start_time?: string | null;
  duration_minutes?: number | null;
}

interface Day {
  date: string;
  activities: Activity[];
}

interface Props {
  tripId: string;
  tripTitle: string;
  days: Day[];
}

export function ExportMenu({ tripId, tripTitle, days }: Props) {
  const [open, setOpen] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function onClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", onClick);
    return () => document.removeEventListener("mousedown", onClick);
  }, []);

  function downloadIcal() {
    window.open(`/api/trips/${tripId}/export/ical`, "_blank");
    setOpen(false);
  }

  function openGoogleCalendar() {
    const allActivities: { activity: Activity; date: string }[] = [];
    for (const day of days) {
      for (const activity of day.activities) {
        if (activity.start_time) allActivities.push({ activity, date: day.date });
      }
    }
    if (allActivities.length === 0) return;
    const first = allActivities[0];
    const durationMins = first.activity.duration_minutes ?? 60;
    const { start, end } = buildActivityDateRange(first.date, first.activity.start_time!, durationMins);
    const url = googleCalendarUrl(
      first.activity.title,
      first.activity.description ?? "",
      first.activity.address ?? "",
      start,
      end
    );
    window.open(url, "_blank");
    setOpen(false);
  }

  async function downloadPdf() {
    setPdfLoading(true);
    setOpen(false);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxWidth = pageWidth - margin * 2;
      let y = margin;

      function checkPage(needed = 10) {
        if (y + needed > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          y = margin;
        }
      }

      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text(tripTitle, margin, y);
      y += 12;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 120, 120);
      doc.text(`Generated by TrailGuide AI`, margin, y);
      doc.setTextColor(0, 0, 0);
      y += 10;

      for (const day of days) {
        checkPage(16);
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        const dayLabel = new Date(day.date + "T12:00:00").toLocaleDateString("en-US", {
          weekday: "long", month: "long", day: "numeric",
        });
        doc.text(dayLabel, margin, y);
        y += 2;
        doc.setDrawColor(45, 106, 79);
        doc.setLineWidth(0.5);
        doc.line(margin, y, margin + maxWidth, y);
        y += 6;

        for (const activity of day.activities) {
          checkPage(20);
          doc.setFontSize(11);
          doc.setFont("helvetica", "bold");
          const timeLabel = activity.start_time ? `${activity.start_time}  ` : "";
          doc.text(`${timeLabel}${activity.title}`, margin, y);
          y += 5;

          if (activity.address) {
            doc.setFontSize(9);
            doc.setFont("helvetica", "italic");
            doc.setTextColor(100, 100, 100);
            doc.text(activity.address, margin + 3, y);
            doc.setTextColor(0, 0, 0);
            y += 4;
          }

          if (activity.description) {
            doc.setFontSize(9);
            doc.setFont("helvetica", "normal");
            const lines = doc.splitTextToSize(activity.description, maxWidth - 3);
            for (const line of lines) {
              checkPage(5);
              doc.text(line, margin + 3, y);
              y += 4;
            }
          }
          y += 3;
        }
        y += 4;
      }

      doc.save(`${tripTitle.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-itinerary.pdf`);
    } finally {
      setPdfLoading(false);
    }
  }

  return (
    <div className="relative" ref={ref}>
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-2 px-4 py-2 rounded-xl border border-border text-sm font-medium hover:bg-muted transition-colors"
      >
        <Download className="w-4 h-4" />
        Export
        <ChevronDown className="w-3 h-3" />
      </button>

      {open && (
        <div className="absolute right-0 mt-2 w-52 bg-card border border-border rounded-xl shadow-lg z-10 overflow-hidden">
          <button
            onClick={downloadIcal}
            className="flex items-center gap-3 w-full px-4 py-3 text-sm hover:bg-muted transition-colors text-left"
          >
            <Calendar className="w-4 h-4 text-primary" />
            <div>
              <div className="font-medium">Calendar (.ics)</div>
              <div className="text-xs text-muted-foreground">Works with all calendar apps</div>
            </div>
          </button>
          <button
            onClick={openGoogleCalendar}
            className="flex items-center gap-3 w-full px-4 py-3 text-sm hover:bg-muted transition-colors text-left border-t border-border"
          >
            <Calendar className="w-4 h-4 text-blue-500" />
            <div>
              <div className="font-medium">Google Calendar</div>
              <div className="text-xs text-muted-foreground">Opens first activity in browser</div>
            </div>
          </button>
          <button
            onClick={downloadPdf}
            disabled={pdfLoading}
            className="flex items-center gap-3 w-full px-4 py-3 text-sm hover:bg-muted transition-colors text-left border-t border-border disabled:opacity-50"
          >
            <FileText className="w-4 h-4 text-orange-500" />
            <div>
              <div className="font-medium">{pdfLoading ? "Generating…" : "PDF Itinerary"}</div>
              <div className="text-xs text-muted-foreground">Full printable schedule</div>
            </div>
          </button>
        </div>
      )}
    </div>
  );
}
